- db/V1__initial_schema.sql
- server/src/schema.graphql
> Setup initial database and GraphQL schema

- client/src/components/CreateNonFungiblePage/Form.tsx
- client/src/generated/graphql_schema.tsx
- server/src/generated/graphql_schema.ts
- server/src/index.ts
- server/src/resolvers/mutations/index.ts
- server/src/schema.graphql
> feat: Add owner_address to form and GQL mutation

- client/src/api/ipfsUploader.ts
- client/src/components/App/App.tsx
- client/src/components/AssetsPage/AssetCard.tsx
- client/src/components/AssetsPage/index.tsx
- client/src/components/AssetsPage/useNftsQuery.ts
- client/src/components/CreateNonFungiblePage/Form.tsx
- client/src/components/CreateNonFungiblePage/index.tsx
- client/src/components/CreateNonFungiblePage/useCreateMutation.ts
- client/src/components/Page/Header.tsx
Implemented:
- Integration with the server
- Required fields validation
- Assets page
> Client/Server Integration & Assets Page

- client/src/components/AssetsPage/index.tsx
- client/src/components/AssetsPage/useNftsQuery.ts
- client/src/generated/graphql_schema.tsx
- server/src/generated/graphql_schema.ts
- server/src/resolvers/queries/index.ts
- server/src/schema.graphql
Implemented filtering of assets by the account selected by wallet on the client &
server sides
> feat: Implement filtering of assets by selected account

- client/src/components/Page/AddressInfo.tsx
- client/src/components/Page/Header.tsx
Account balance ticks (changes) every 10 seconds.
> Show account and account balance

- client/src/api/nftContract.ts
- client/src/components/AssetsPage/AssetCard.tsx
- client/src/components/AssetsPage/AssetTransfer.tsx
- client/src/components/AssetsPage/ContractsTitle.tsx
- client/src/components/AssetsPage/index.tsx
- client/src/components/AssetsPage/useNftsQuery.ts
- client/src/components/CreateNonFungiblePage/LeftSide.tsx
- client/src/components/CreateNonFungiblePage/index.tsx
- client/src/components/common/Copyable.tsx
- client/src/components/common/validators.ts
- client/src/generated/graphql_schema.tsx
- server/src/generated/graphql_schema.ts
- server/src/resolvers/queries/index.ts
- server/src/resolvers/queries/nfts.ts
- server/src/schema.graphql
The following is implemented in this version:
- NFT Transfer
- Asset Card rendering improvements
- Asset Card link to tzindex
- Create page alert when not connected to wallet
> Token Transfer Implementaton

- client/src/components/AssetsPage/Assets.tsx
- client/src/components/AssetsPage/ContractsFilter.tsx
- client/src/components/AssetsPage/index.tsx
- client/src/components/CreateNonFungiblePage/Form.tsx
- client/src/components/CreateNonFungiblePage/RightSide.tsx
- client/src/components/CreateNonFungiblePage/index.tsx
- client/src/components/WalletConnector/index.tsx
- client/src/components/common/useContractNamesQuery.ts
- client/src/generated/graphql_schema.tsx
- server/src/generated/graphql_schema.ts
- server/src/resolvers/queries/contractNames.ts
- server/src/resolvers/queries/index.ts
- server/src/resolvers/queries/nfts.ts
- server/src/schema.graphql
This version include:
- Message text changes
- Blocking Asset page before connection to wallet
- Showing only relevant contracts in Asset Page
> feat: Asset Page Improvements

- client/src/components/AssetsPage/AssetCard.tsx
- client/src/components/CreateNonFungiblePage/ImagePreview.tsx
- client/src/components/CreateNonFungiblePage/NewContract.tsx
- client/src/components/CreateNonFungiblePage/RightSide.tsx
Includes:
- Links to contracts and IPFS image, also image in Asset is clickable
- New contract view is in dropdown rather than with a button
> UI Cleanup

- client/src/components/App/App.tsx
- client/src/components/AssetDetailsPage/Actions.tsx
- client/src/components/AssetDetailsPage/AssetDescription.tsx
- client/src/components/AssetDetailsPage/Typography.tsx
- client/src/components/AssetDetailsPage/index.tsx
- client/src/components/AssetsPage/AssetCard.tsx
- client/src/components/AssetsPage/Assets.tsx
- client/src/components/AssetsPage/index.tsx
- client/src/components/CreateNonFungiblePage/index.tsx
- client/src/components/common/NotConnectedAlert.tsx
- client/src/components/common/PageTitle.tsx
- client/src/components/common/useNftsQuery.ts
- client/src/config/index.ts
#96 Created Asset Details Page
> Created Asset Details Page

- client/src/components/CreateNonFungiblePage/FileUpload.tsx
- client/src/components/CreateNonFungiblePage/Form.tsx
- client/src/components/CreateNonFungiblePage/Preview.tsx
- client/src/components/CreateNonFungiblePage/index.tsx
- client/src/components/CreateNonFungiblePage/reducer.ts
The implementation of file upload using react-dropzone.
> Alex kooper/dropzone

- contracts/ligo/src/fixed_price_sale_market.mligo
- contracts/ligo/src/fixed_price_sale_market_tez.mligo
This should resolve issue #130
> Remove update operators from market contract

- contracts/ligo/src/tzip16-compat/fa2_multi_nft_asset.mligo
- contracts/ligo/src/tzip16-compat/fa2_multi_nft_faucet.mligo
- contracts/src/nft-contracts-tzip16.ts
The spec only requires that the 'description' and 'interfaces' fields
to be defined IIRC
This should resolve issue #131
> populate tzip-16 contract data when contracts are originated

- client/src/components/CreateNonFungiblePage/FileUpload.tsx
- client/src/components/CreateNonFungiblePage/Form.tsx
- client/src/components/CreateNonFungiblePage/Preview.tsx
- client/src/components/CreateNonFungiblePage/index.tsx
- client/src/components/common/Notifications.tsx
- client/src/reducer/async/actions.ts
- client/src/reducer/slices/createNft.ts
- client/src/reducer/slices/notifications.ts
- client/src/reducer/validators/createNft.ts
> feat: Upload artifact files on token creation submit

- contracts/bin/fa2_multi_nft_asset.tz
- contracts/bin/fa2_multi_nft_faucet.tz
- contracts/bin/fa2_nft_factory.tz
- contracts/bin/fixed_price_sale_market_tez.tz
- contracts/ligo/src/fa2_multi_nft_token.mligo
- contracts/ligo/src/fa2_nft_factory.mligo
- contracts/ligo/src/fixed_price_sale_market_tez.mligo
Audit comments here: https://www.notion.so/Mini-audit-report-for-Fixed-price-sale-contract-547ff83d20d747a3ada536b885c5e54e
> Fixed price sale mini-audit

- contracts/test/auction/auction.test.ts
Test with `npm run test --findRelatedTests ./test/auction/auction.test.ts`
> added bid unit tests

- README.md
Added docker and yarn dependencies
> updated readme for depend.

- CONTRIBUTING.md
- README.md
Added contribution guidelines to give the community direction in submitting feedback, fixes, and enhancements.
> added contribution guidelines

- README.md
Updated shield to drop docker needs (sandbox only) and updated version shield.
> changed shields to reflect version

- src/lib/nfts/queries.ts
My take on this; show the contract if it is 1) FA2 (tagged as fa2 in BCD) and 2) has the entrypoints that Minter needs.
> Support any FA2 with required entrypoints.

- src/components/CreateNonFungiblePage/Preview.tsx
- src/components/CreateNonFungiblePage/StatusModal.tsx
Added carbon savings message to token creation modal.
Resolves #206
> Carbon savings message on creation of NFT

- src/components/CreateNonFungiblePage/FileUpload.tsx
> Add video metadata types to file upload page.

- src/components/common/Header.tsx
> Add badge to display network when not on mainnet.

- src/components/Collections/Catalog/index.tsx
> Link contract to explorer GUI.

- README.md
Getting rid of the need to manually update the shield on each release - draws directly from the latest cut.
> Shield Auto Updates

- src/components/Collections/Catalog/TokenGrid.tsx
Initial PR to collect commits related to improving the responsiveness of the UI.
> Responsive UI

- src/components/SplashPage/index.tsx
> Modified splash screen to be responsive 

- src/components/Collections/TokenDetail/index.tsx
> Fix the video hiding buttons the and back button

- src/lib/system.ts
- src/lib/util/ipfs.ts
`gateway.ipfs.io` has been causing some issues. Switching to `gateway.pinata.cloud`
> Switch IPFS gateway to Pinata

- src/components/App/index.tsx
Marketplace now begins loading client side immediately upon login.
#308
> [Hotfix: Mrkt] -- "faster" load

- src/reducer/async/queries.ts
> [Issue] -- #349

- src/components/Collections/Catalog/CollectionDisplay.tsx
- src/components/Collections/Catalog/CollectionsDropdown.tsx
- src/components/CreateNonFungiblePage/CollectionSelect.tsx
Number of UI changes, such as #356 and #363
> UI Changes - #356, #363 

- config/mainnet.json
- config/sandbox.json
- config/testnet.json
- src/components/Collections/Catalog/CollectionDisplay.tsx
- src/components/Collections/TokenDetail/index.tsx
- src/components/Marketplace/Catalog/FeaturedToken.tsx
- src/components/Marketplace/Catalog/TokenCard.tsx
- src/components/Marketplace/Catalog/index.tsx
- src/lib/system.ts
- src/lib/util/ipfs.ts
This allows easy switching when pinata is broken:
Alternatives:
- "ipfsGateway": "https://cloudflare-ipfs.com"
- "ipfsGateway": "https://ipfs.fleek.co"
> Add ipfsGateway to config

- README.md
Updated copy to reflect tzkt indexing.
> Updated to tzkt

- src/components/Collections/TokenDetail/index.tsx
- src/components/Marketplace/Catalog/index.tsx
* Individual Asset onclick expand
* TokenCard transition increased
* Fullscreen asset view backdrop darker
> style: tokencard/fullscreen/individual-asset

- src/components/Collections/TokenDetail/index.tsx
> fix: TokenDetail video width

- src/components/common/modals/BuyToken.tsx
- src/components/common/modals/CancelTokenSale.tsx
- src/components/common/modals/FormModal.tsx
- src/components/common/modals/SellToken.tsx
>  fix: disable buttons when loading

- docs/batch_minting.md
- docs/batch_template_testnet.csv
- src/components/CreateNonFungiblePage/FileUpload.tsx
- src/lib/nfts/queries.ts
- src/reducer/async/actions.ts
- Add batch_template_testnet.csv (with testnet contract id)
- Remove csv filter on drop zone (which was broken in windows chrome)
- Fix duplicate metadata attributes
- Sort tokens by id (descending)
> Mint with Csv (Fixes)

- config/sandbox.json
- docker-compose.yml
- docker/multiple-postgresql-databases.sh
- docker/tzkt-api-appsettings.json
- docker/tzkt-sync-appsettings.json
> Fixing sandbox mode

- README.md
Added florencenet to the readme as well as a note on batch minting
> Updated to reflect testnet and batching changes
